services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    disk:
       name: n8n-data
       mountPath: /home/node/.n8n
       sizeGB: 1
