services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE         # O valor será configurado no painel do Render
      - key: DB_HOST
      - key: DB_PORT
      - key: DB_DATABASE
      - key: DB_USER
      - key: DB_PASSWORD
